sudo: required
services:
  - docker
script:
  - docker run --rm -it -v "$(pwd)":/home/rust/src ekidd/rust-musl-builder sh -c 'sudo chown -R rust . && cargo test && cargo build --release'

cache: cargo

notifications:
  email:
    on_success: never

before_deploy:
  - ./ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: "fdLXKxM5eLdQq/TrFjwp2NpJP6e7zp4yjtxaXvHSvETkEGz5ZiLFbIhP0Qql6f4qjDAfipoQZUD47ibYlcKDYoX9iXDOPWGqpTvrmGer43voZRhPJXuqfJIevRBnFm15xZKJtnIa4COF+LhOSCLsueajtZQOC1MV6GV2E1PBnkprawtusvmnjQDo2KiEBwQ4W5VfKtemXoihc+JF+efwpCv9tvsjkhtiyxxxFXVb1wGa+kY3vIBzXm7lao8oYhq9qS8nD/dsxZ3HywKM2y3YJDxwDg+S2e+NutleppnqDbjr9NjijF382PJlLhqTBu3C+Zi+yLZeTGPf4fR14Y8ZoycTYkPg+2fjL5HbIWd/NtHQVF25Pk3vkgMX6D+jLJ5pLGatl7eYw1cSolNy/RGmIzOsgFTy2a1N4kVJB+azcLLQHaG6UPL/DhN6xozlrtOR7PyIBSvW6DZrLmaCgIPquuZ4iHtNJZkEFYaL+/NIsgMHiSGNNtaY5jzDifFL/FKzG6/nu6MCagxIME2sLcoCWAmVCiA/JKKxc0+1+S3Z+duHcJ+WtRb7dLDZAr23qo1CmEWK3W60XMGVHGO+RuYu7+0nVUqe3GY3TRDWmxkz+t/VHUtYKQHc2jixSWeK2o5j8yeU7LnpS/H3rCnm1CJmiWi7wyGUx78GPaczHtgcOdM="
  file_glob: true
  file:
    - deploy/*
  skip_cleanup: true
  on:
    tags: true
