[package]
name = "crypto"
version = "0.1.0"
authors = ["Valentin Brandl <vbrandl@riseup.net>"]
license = "MIT/Apache-2.0"

[dependencies]
failure = "0.1.6"
hex = "0.3.2"
ring = "0.13.5"

[dev-dependencies]
proptest = "0.9.4"
